### ISSUE TITLE
Characters in books are too long or too short compared to vanilla

### ISSUE THREAD

**Issue by Aeldit** [Xetheon/mc-geometric-font#2]
Here is what it looks like in vanilla
![2023-01-14_09 48 31](https://user-images.githubusercontent.com/81476169/212464154-0ecf17e5-fa66-4626-8b98-da1f1519fce1.png)

And here it is with the pack
![2023-01-14_09 49 06](https://user-images.githubusercontent.com/81476169/212464160-af85470e-9fdc-4ccf-9bdd-60820f5f481e.png)

We can see that the character << is longer than in vanilla and the "-" is shorter

**Comment by Zentheon** [comment]
While that behavior is somewhat intentional, I can see why that would cause issues. The next update will convert it to TrueType so I'll make sure to adjust it then

**Comment by Aeldit** [comment]
Thanks :)

**Comment by Zentheon** [comment]
This has been fixed since the remake, though still exists in legacy. Gonna close for now though
