### ISSUE TITLE
Some core shaders are broken by this resource pack

### ISSUE THREAD

**Issue by Aeldit** [Xetheon/mc-geometric-font#3]
I am using a core shader to change the text colour in some GUIs (block inventories), but the colour stays the same with the Geometric font resource pack. The concerned files here are `rendertype_text_intensity.fsh` and `rendertype_text.fsh`

(I can't put images to demonstrate right now because GitHub won't let me, but I will put them as soon as it works)

**Comment by Zentheon** [comment]
Hey! Sorry I'm a bit late but mind linking a source for these shaders? Also just to be sure, the font version used is from a full release?

**Comment by Aeldit** [comment]
Here is the link to the shaders (there's 3) : https://github.com/Aeldit/MC-Resource-Packs/tree/main/Smooth%20GUI/1.19.4/assets/minecraft/shaders/core

And the version I use is Geo Font 1.1 Scale 3 (I downloaded it from Modrinth)

Edit: only 2 of the shaders are used to make the text go white, not the 3

**Comment by Zentheon** [comment]
It took me a bit too long to realize while troubleshooting that current versions of GeoFont all use a slightly off-white color which the shaders aren't detecting. It wasn't intended like that, just an accidental byproduct of when I first developed it, but good to know it's being broken by something not supposed to be apart of the font in the first place.

I'll get a fix for this released in a bit.

**Comment by Zentheon** [comment]
Done! And the pack is now up to date on all platforms for the first time as well.
