### ISSUE TITLE
Caxton support broken

### ISSUE THREAD

**Issue by PencilVoid** [Xetheon/mc-geometric-font#6]
I can't tell when it occured but it seems that at some point Caxton changed the way it recognises fonts, and as such the latest version of the resource pack is not picked up by Caxton.

**Comment by Zentheon** [comment]
Sure has! Seems like a pretty simple change to the way the provider is implemented. Will have an update pushed soon.

**Comment by Zentheon** [comment]
Done! Thanks for pointing this out

Links: 
[Github](https://github.com/Zentheon/mc-geometric-font/releases/tag/2-%26-edge-v1.1.1)
[Modrinth (GeoFont 2)](https://modrinth.com/resourcepack/geometric-font-2)
[Modrinth (GeoFont Edge)](https://modrinth.com/resourcepack/geometric-font-edge/version/1.1.1)
